In [1]:
"""
Real loop subtract random loop

"""

'\nReal loop subtract random loop\n\n'

In [1]:
import os, sys, glob
import numpy as np
import pandas as pd
import pyranges as pr
#import glbase3

In [2]:
# 

path = '../data/real_loop/ctcf.rad21/'
file = glob.glob(os.path.join(path,'*.txt'))
d1 = []
for f in file:
    d1.append(pd.read_csv(f,comment='#',header=None))
data = pd.concat(d1,axis=1)
print(data)

          0        0        0        0        0        0        0        0  \
0   1552122  2779308  2359505  4248417  2530801  4556959  3199549  5730413
1    476961   586890   723592   887041   776762   950602   980571  1195588
2    162677   183412   242219   268860   259477   287835   325950   359684
3     86127   103366   126771   150682   135879   161371   168935   199484
4     57615    70140    85280   101456    91533   108890   112640   134518
5     42044    51900    62545    75235    67123    80454    82688    99170
6     32822    40146    48423    58141    51964    62249    63768    76526
7     26035    32095    38730    46275    41484    49471    51054    60582
8     21210    25830    31477    37133    33868    39727    41501    48429
9     17501    21432    26261    31228    28116    33375    34170    40807
10    14579    17638    22162    25590    23642    27452    28883    33571
11    12627    14923    18958    21596    20329    23123    24830    28423
12    10533    12537    15743    18214    16899    19573    20793    24029
13     9042    10888    13670    15839    14605    16952    17866    20566
14     7846     9336    11778    13523    12567    14403    15520    17656
15     7022     8004    10450    11477    11117    12303    13598    15272
16     6042     6982     9144    10007     9721    10672    12040    13178
17     5348     5947     8102     8596     8655     9248    10683    11548
18     4581     5156     7014     7471     7508     7952     9252     9954
19     7900     8506    11845    12381    12749    13141    15762    16333

          0        0        0        0        0         0        0        0  \
0   2925137  5257769  2922057  5250576  6052493  10796545  2777194  4963443
1    895768  1098194   897601  1096631  1860107   2254540   849084  1034665
2    299175   332671   299248   329372   618848    677341   282481   309573
3    156531   185038   156195   183714   321400    376635   147227   172738
4    104667   125376   104463   124030   215256    253828    99432   116504
5     76730    92383    77097    91913   157405    187015    72749    86247
6     59250    71004    59692    70885   121621    144140    56638    66791
7     47500    56490    48134    56162    97165    113977    45577    53170
8     38228    45504    38920    45728    78652     91827    36811    43082
9     31920    38035    32487    38139    65318     76488    31021    36204
10    26792    31186    27101    31436    54556     62993    26013    29660
11    22927    26244    23282    26454    46520     52790    22246    25250
12    19083    22324    19568    22463    38915     44780    18704    21620
13    16471    19158    16833    19234    33739     38041    16276    18522
14    14281    16383    14664    16377    29152     32446    14115    15766
15    12518    13994    12955    14134    25556     27908    12475    13435
16    11050    12050    11424    12317    22414     23947    10993    11860
17     9806    10433     9990    10625    19679     20775     9642    10305
18     8451     9203     8601     9325    17013     18021     8366     8927
19    14239    14902    14696    15055    28671     29501    14095    14530

          0        0
0   1060967  1924250
1    324135   401889
2    109319   121795
3     57518    68763
4     39252    46657
5     28952    34727
6     22512    26987
7     18587    21549
8     14933    17684
9     12692    14889
10    10641    12418
11     9128    10464
12     7714     8933
13     6779     7741
14     5800     6611
15     5162     5633
16     4531     5030
17     4072     4308
18     3524     3787
19     5974     6135

In [25]:
filename = []
for f in file:
    rep = os.path.split(f)[1].split('primed_')[1].split('.bed')[0]
    fn = os.path.split(f)[1].split('_peaks')[0]
    filename.append(fn + '_' + rep)
print(filename)

['CTCF_35846_r1', 'CTCF_35846_r2', 'CTCF_36632_r1', 'CTCF_36632_r2', 'CTCF_45230_r1', 'CTCF_45230_r2', 'CTCF_46184_r1', 'CTCF_46184_r2', 'CTCF_50988_r1', 'CTCF_50988_r2', 'RAD21_45689_r1', 'RAD21_45689_r2', 'RAD21_46164_r1', 'RAD21_46164_r2', 'RAD21_91096_r1', 'RAD21_91096_r2', 'RAD21_94415_r1', 'RAD21_94415_r2']

In [26]:
data.columns = filename
print(data)

    CTCF_35846_r1  CTCF_35846_r2  CTCF_36632_r1  CTCF_36632_r2  CTCF_45230_r1  \
0         1552122        2779308        2359505        4248417        2530801
1          476961         586890         723592         887041         776762
2          162677         183412         242219         268860         259477
3           86127         103366         126771         150682         135879
4           57615          70140          85280         101456          91533
5           42044          51900          62545          75235          67123
6           32822          40146          48423          58141          51964
7           26035          32095          38730          46275          41484
8           21210          25830          31477          37133          33868
9           17501          21432          26261          31228          28116
10          14579          17638          22162          25590          23642
11          12627          14923          18958          21596          20329
12          10533          12537          15743          18214          16899
13           9042          10888          13670          15839          14605
14           7846           9336          11778          13523          12567
15           7022           8004          10450          11477          11117
16           6042           6982           9144          10007           9721
17           5348           5947           8102           8596           8655
18           4581           5156           7014           7471           7508
19           7900           8506          11845          12381          12749

    CTCF_45230_r2  CTCF_46184_r1  CTCF_46184_r2  CTCF_50988_r1  CTCF_50988_r2  \
0         4556959        3199549        5730413        2925137        5257769
1          950602         980571        1195588         895768        1098194
2          287835         325950         359684         299175         332671
3          161371         168935         199484         156531         185038
4          108890         112640         134518         104667         125376
5           80454          82688          99170          76730          92383
6           62249          63768          76526          59250          71004
7           49471          51054          60582          47500          56490
8           39727          41501          48429          38228          45504
9           33375          34170          40807          31920          38035
10          27452          28883          33571          26792          31186
11          23123          24830          28423          22927          26244
12          19573          20793          24029          19083          22324
13          16952          17866          20566          16471          19158
14          14403          15520          17656          14281          16383
15          12303          13598          15272          12518          13994
16          10672          12040          13178          11050          12050
17           9248          10683          11548           9806          10433
18           7952           9252           9954           8451           9203
19          13141          15762          16333          14239          14902

    RAD21_45689_r1  RAD21_45689_r2  RAD21_46164_r1  RAD21_46164_r2  \
0          2922057         5250576         6052493        10796545
1           897601         1096631         1860107         2254540
2           299248          329372          618848          677341
3           156195          183714          321400          376635
4           104463          124030          215256          253828
5            77097           91913          157405          187015
6            59692           70885          121621          144140
7            48134           56162           97165          113977
8            38920           45728           78652           91827
9            32487           38139           65318           76488
10           27101           31436           54556           62993
11           23282           26454           46520           52790
12           19568           22463           38915           44780
13           16833           19234           33739           38041
14           14664           16377           29152           32446
15           12955           14134           25556           27908
16           11424           12317           22414           23947
17            9990           10625           19679           20775
18            8601            9325           17013           18021
19           14696           15055           28671           29501

    RAD21_91096_r1  RAD21_91096_r2  RAD21_94415_r1  RAD21_94415_r2
0          2777194         4963443         1060967         1924250
1           849084         1034665          324135          401889
2           282481          309573          109319          121795
3           147227          172738           57518           68763
4            99432          116504           39252           46657
5            72749           86247           28952           34727
6            56638           66791           22512           26987
7            45577           53170           18587           21549
8            36811           43082           14933           17684
9            31021           36204           12692           14889
10           26013           29660           10641           12418
11           22246           25250            9128           10464
12           18704           21620            7714            8933
13           16276           18522            6779            7741
14           14115           15766            5800            6611
15           12475           13435            5162            5633
16           10993           11860            4531            5030
17            9642           10305            4072            4308
18            8366            8927            3524            3787
19           14095           14530            5974            6135

In [5]:
## load bed files
bedpath = '../data/bed/ctcf.rad21/'
bedfile = glob.glob(os.path.join(bedpath,'*.bed'))
peaknum = []
for b in bedfile:
    bed = pr.read_bed(b)
    peaknum.append(len(bed))

In [6]:
peaknum = np.repeat(peaknum, 2)
peaknum

array([ 70084,  70084,  82900,  82900,  87184,  87184, 101440, 101440,
        97256,  97256,  92669,  92669, 151864, 151864,  86582,  86582,
        51993,  51993])

In [27]:
normed = data / peaknum
normed.head()

,CTCF_35846_r1,CTCF_35846_r2,CTCF_36632_r1,CTCF_36632_r2,CTCF_45230_r1,CTCF_45230_r2,CTCF_46184_r1,CTCF_46184_r2,CTCF_50988_r1,CTCF_50988_r2,RAD21_45689_r1,RAD21_45689_r2,RAD21_46164_r1,RAD21_46164_r2,RAD21_91096_r1,RAD21_91096_r2,RAD21_94415_r1,RAD21_94415_r2
0,22.146596,39.656812,28.462063,51.247491,29.028274,52.268295,31.541295,56.490664,30.076674,54.061127,31.532195,56.659465,39.854692,71.093511,32.075882,57.326500,20.405958,37.009790
1,6.805562,8.374094,8.728492,10.700133,8.909456,10.903400,9.666512,11.786159,9.210414,11.291787,9.686098,11.833850,12.248505,14.845783,9.806703,11.950117,6.234205,7.729675
2,2.321172,2.617031,2.921821,3.243185,2.976200,3.301466,3.213229,3.545781,3.076160,3.420570,3.229214,3.554285,4.075014,4.460181,3.262583,3.575489,2.102572,2.342527
3,1.228911,1.474887,1.529204,1.817636,1.558531,1.850924,1.665369,1.966522,1.609474,1.902587,1.685515,1.982475,2.116367,2.480081,1.700434,1.995080,1.106264,1.322543
4,0.822085,1.000799,1.028709,1.223836,1.049883,1.248968,1.110410,1.326084,1.076201,1.289134,1.127270,1.338420,1.417426,1.671417,1.148414,1.345591,0.754948,0.897371

In [8]:
back = pd.read_csv('ctcf_rad21_meanback.txt', sep='\t')
back.head()

,CTCF_35846_r1,CTCF_35846_r2,CTCF_36632_r1,CTCF_36632_r2,CTCF_45230_r1,CTCF_45230_r2,CTCF_46184_r1,CTCF_46184_r2,CTCF_50988_r1,CTCF_50988_r2,RAD21_45689_r1,RAD21_45689_r2,RAD21_46164_r1,RAD21_46164_r2,RAD21_91096_r1,RAD21_91096_r2,RAD21_94415_r1,RAD21_94415_r2
0,23.964474,41.920903,23.964474,41.920903,23.964474,41.920903,23.964474,41.920903,23.964474,41.920903,23.964474,41.920903,23.964474,41.920903,23.964474,41.920903,23.964474,41.920903
1,7.282030,8.758022,7.282030,8.758022,7.282030,8.758022,7.282030,8.758022,7.282030,8.758022,7.282030,8.758022,7.282030,8.758022,7.282030,8.758022,7.282030,8.758022
2,2.457836,2.676240,2.457836,2.676240,2.457836,2.676240,2.457836,2.676240,2.457836,2.676240,2.457836,2.676240,2.457836,2.676240,2.457836,2.676240,2.457836,2.676240
3,1.274910,1.480195,1.274910,1.480195,1.274910,1.480195,1.274910,1.480195,1.274910,1.480195,1.274910,1.480195,1.274910,1.480195,1.274910,1.480195,1.274910,1.480195
4,0.843673,0.986217,0.843673,0.986217,0.843673,0.986217,0.843673,0.986217,0.843673,0.986217,0.843673,0.986217,0.843673,0.986217,0.843673,0.986217,0.843673,0.986217

In [28]:
print(normed.shape)
print(back.shape)

(20, 18)
(20, 18)

In [29]:
sub = []
for x in range(0, 17):
    sub.append(normed.iloc[:,x] - back.iloc[:,x])
subed = pd.concat(sub, axis=1)

In [30]:
subed.head()

,CTCF_35846_r1,CTCF_35846_r2,CTCF_36632_r1,CTCF_36632_r2,CTCF_45230_r1,CTCF_45230_r2,CTCF_46184_r1,CTCF_46184_r2,CTCF_50988_r1,CTCF_50988_r2,RAD21_45689_r1,RAD21_45689_r2,RAD21_46164_r1,RAD21_46164_r2,RAD21_91096_r1,RAD21_91096_r2,RAD21_94415_r1
0,-1.817879,-2.264092,4.497589,9.326587,5.063799,10.347391,7.576821,14.569761,6.112200,12.140224,7.567721,14.738562,15.890218,29.172608,8.111408,15.405596,-3.558516
1,-0.476468,-0.383928,1.446462,1.942111,1.627426,2.145378,2.384482,3.028138,1.928384,2.533765,2.404068,3.075828,4.966475,6.087761,2.524673,3.192095,-1.047826
2,-0.136665,-0.059209,0.463985,0.566945,0.518363,0.625226,0.755393,0.869541,0.618324,0.744331,0.771377,0.878045,1.617178,1.783942,0.804747,0.899249,-0.355265
3,-0.045999,-0.005308,0.254294,0.337441,0.283621,0.370729,0.390459,0.486327,0.334564,0.422392,0.410605,0.502280,0.841457,0.999886,0.425524,0.514885,-0.168646
4,-0.021588,0.014583,0.185036,0.237619,0.206210,0.262751,0.266737,0.339868,0.232528,0.302917,0.283597,0.352203,0.573753,0.685200,0.304741,0.359375,-0.088726

In [31]:
subed.to_csv("ctcf_rad21_subed.txt", sep='\t', index=False)