In [38]:
"""

Get z-score of each row

"""

'\n\nGet z-score of each row\n\n'

In [39]:
import os, sys, glob
import numpy as np
import pandas as pd
import pyranges as pr

In [40]:
subed = pd.read_csv('ctcf_rad21_subed.txt', sep='\t')

In [41]:
subed.head()

,CTCF_35846_r1,CTCF_35846_r2,CTCF_36632_r1,CTCF_36632_r2,CTCF_45230_r1,CTCF_45230_r2,CTCF_46184_r1,CTCF_46184_r2,CTCF_50988_r1,CTCF_50988_r2,RAD21_45689_r1,RAD21_45689_r2,RAD21_46164_r1,RAD21_46164_r2,RAD21_91096_r1,RAD21_91096_r2,RAD21_94415_r1
0,-1.817879,-2.264092,4.497589,9.326587,5.063799,10.347391,7.576821,14.569761,6.112200,12.140224,7.567721,14.738562,15.890218,29.172608,8.111408,15.405596,-3.558516
1,-0.476468,-0.383928,1.446462,1.942111,1.627426,2.145378,2.384482,3.028138,1.928384,2.533765,2.404068,3.075828,4.966475,6.087761,2.524673,3.192095,-1.047826
2,-0.136665,-0.059209,0.463985,0.566945,0.518363,0.625226,0.755393,0.869541,0.618324,0.744331,0.771377,0.878045,1.617178,1.783942,0.804747,0.899249,-0.355265
3,-0.045999,-0.005308,0.254294,0.337441,0.283621,0.370729,0.390459,0.486327,0.334564,0.422392,0.410605,0.502280,0.841457,0.999886,0.425524,0.514885,-0.168646
4,-0.021588,0.014583,0.185036,0.237619,0.206210,0.262751,0.266737,0.339868,0.232528,0.302917,0.283597,0.352203,0.573753,0.685200,0.304741,0.359375,-0.088726

In [42]:
# calculate the z-score for each row

rowmean = subed.mean(axis=1)
rowsd = subed.std(axis=1)

In [43]:
print(rowmean.head())
print(rowsd.head())

0    8.992941
1    2.198754
2    0.668559
3    0.373795
4    0.264518
dtype: float64
0    7.991285
1    1.784046
2    0.537891
3    0.285692
4    0.190230
dtype: float64

In [48]:
zmat = subed.sub(rowmean, axis=0).div(rowsd, axis=0)
zmat.head()

,CTCF_35846_r1,CTCF_35846_r2,CTCF_36632_r1,CTCF_36632_r2,CTCF_45230_r1,CTCF_45230_r2,CTCF_46184_r1,CTCF_46184_r2,CTCF_50988_r1,CTCF_50988_r2,RAD21_45689_r1,RAD21_45689_r2,RAD21_46164_r1,RAD21_46164_r2,RAD21_91096_r1,RAD21_91096_r2,RAD21_94415_r1
0,-1.352826,-1.408664,-0.562532,0.041751,-0.491678,0.169491,-0.177208,0.697863,-0.360485,0.393839,-0.178347,0.718986,0.863100,2.525209,-0.110312,0.802456,-1.570643
1,-1.499525,-1.447654,-0.421678,-0.143855,-0.320243,-0.029919,0.104105,0.464889,-0.151549,0.187781,0.115083,0.491620,1.551373,2.179880,0.182685,0.556791,-1.819785
2,-1.497001,-1.353002,-0.380326,-0.188913,-0.279231,-0.080561,0.161434,0.373647,-0.093394,0.140867,0.191150,0.389457,1.763588,2.073620,0.253188,0.428878,-1.903403
3,-1.469394,-1.326964,-0.418286,-0.127250,-0.315632,-0.010730,0.058328,0.393894,-0.137319,0.170103,0.128846,0.449734,1.636948,2.191492,0.181067,0.493854,-1.898692
4,-1.504003,-1.313860,-0.417820,-0.141400,-0.306514,-0.009287,0.011665,0.396100,-0.168166,0.201858,0.100295,0.460944,1.625587,2.211442,0.211445,0.498645,-1.856930

In [49]:
zmat.to_csv("ctcf_rad21_zmat.txt", sep='\t', index=False)